return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    -- add more things to the ensure_installed table protecting against community packs modifying it
    opts.ensure_installed = require("astronvim.utils").list_insert_unique(opts.ensure_installed, {
      -- "bash",
      -- "c",
      -- "cpp",
      -- "cmake",
      -- "cvs",
      -- "comment",
      -- "diff",
      -- "dockerfile",
      -- "doxygen",
      -- "git_config",
      -- "git_rebase",
      -- "gitattributes",
      -- "gitcommit",
      -- "gitignore",
      -- "haskell",
      -- "haskell_persistent",
      -- "html",
      -- "css",
      -- "scss",
      -- "javascript",
      -- "json",
      -- "latex",
      -- "lua",
      -- "luadoc",
      -- "luap",
      -- "make",
      -- "markdown",
      -- "markdown_inline",
      -- "pymanifest",
      -- "python",
      -- "rust",
      -- "toml",
      -- "typescript",
      -- "sql",
      -- "ssh_config",
      -- "vim",
      -- "vimdoc",
      -- "yaml"
    })
  end,
}
